### ISSUE TITLE
Selection background is too dim

### ISSUE THREAD

**Issue by heyvito** [widersky/nova-mariana-theme#1]
Hi there! Thank you for porting this theme, it is gorgeous on Nova! <3
It seems the selection background is too dim when compared to Sublime Text. For instance, this is the selection style on Sublime:

<img width="203" alt="image" src="https://user-images.githubusercontent.com/77198/158993240-b3cd17a5-585b-47e2-8f7c-9fb5541d36b2.png">

Whilst this is the style on Nova:

<img width="194" alt="image" src="https://user-images.githubusercontent.com/77198/158993303-9873a133-b91a-473d-a384-c9acc5111650.png">

Do you think it would be possible to make it a bit more visible?

Again, thank you so much!
Cheers! 🌻

**Comment by widersky** [comment]
Hi @heyvito ! I will correct this in an upcoming update, thanks for pointing it out!

**Comment by heyvito** [comment]
Awesome! Thank you so much!
